//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractFactory.java
//  @ Date : 13/04/2016
//  @ Author : 
//
//




public class AbstractFactory {
	public void AbstractFactory() {
	}
	
	public void CreateCliente() {
	}
	
	public void CreateHospede() {
	}
}
