//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Diretor.java
//  @ Date : 13/04/2016
//  @ Author : 
//
//




public class Diretor {
	public void Diretor() {
	}
	
	public void build() {
	}
}
