//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FactoryCliente.java
//  @ Date : 13/04/2016
//  @ Author : 
//
//




public class FactoryCliente extends AbstractFactory {
	public void FactoryCliente() {
	}
	
	public void CreateProductCliente() {
	}
}
