//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FactoryHospede.java
//  @ Date : 13/04/2016
//  @ Author : 
//
//




public class FactoryHospede extends AbstractFactory {
	public void FactoryHospede() {
	}
	
	public void CreateProductHospede() {
	}
}
